name: Mypy

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip3 install ".[test,typing]" mypy;
        rm -rf build;
        
    - name: Run MyPy
      run: |
        mypy .;
 
    - uses: tsuyoshicho/action-mypy@v4
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        execute_command: "mypy ."
        # The action will output fail if there are mypy errors
        level: error