name: Mypy

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install --upgrade setuptools ".[test,typing]" mypy;
 
    - uses: tsuyoshicho/action-mypy@v4
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        # The action will output fail if there are mypy errors
        level: error